/**
 * YouTube Subtitles Utility
 *
 * Fetches subtitles directly from YouTube using the youtube-captions-scraper approach.
 * Provides video ID extraction and subtitle fetching with multiple format support.
 */

/**
 * Extract YouTube video ID from various URL formats or return the ID if already valid
 * @param {string} input - YouTube URL or video ID
 * @returns {string|null} - Video ID or null if invalid
 */
export function extractVideoId(input) {
  if (!input || typeof input !== 'string') {
    return null;
  }

  const trimmed = input.trim();

  // Check if it's already a valid video ID (11 characters, alphanumeric with - and _)
  if (/^[a-zA-Z0-9_-]{11}$/.test(trimmed)) {
    return trimmed;
  }

  // Try to extract from various YouTube URL formats
  const patterns = [
    // Standard watch URLs: youtube.com/watch?v=VIDEO_ID
    /(?:youtube\.com\/watch\?.*v=)([a-zA-Z0-9_-]{11})/,
    // Short URLs: youtu.be/VIDEO_ID
    /(?:youtu\.be\/)([a-zA-Z0-9_-]{11})/,
    // Embed URLs: youtube.com/embed/VIDEO_ID
    /(?:youtube\.com\/embed\/)([a-zA-Z0-9_-]{11})/,
    // YouTube Shorts: youtube.com/shorts/VIDEO_ID
    /(?:youtube\.com\/shorts\/)([a-zA-Z0-9_-]{11})/,
    // YouTube Music: music.youtube.com/watch?v=VIDEO_ID
    /(?:music\.youtube\.com\/watch\?.*v=)([a-zA-Z0-9_-]{11})/,
    // YouTube with timestamp: youtube.com/watch?v=VIDEO_ID&t=123
    /(?:youtube\.com\/watch\?v=)([a-zA-Z0-9_-]{11})(?:&|$)/,
    // Nocookie embed: youtube-nocookie.com/embed/VIDEO_ID
    /(?:youtube-nocookie\.com\/embed\/)([a-zA-Z0-9_-]{11})/,
  ];

  for (const pattern of patterns) {
    const match = trimmed.match(pattern);
    if (match && match[1]) {
      return match[1];
    }
  }

  return null;
}

/**
 * Fetch the YouTube video page and extract caption track URLs
 * @param {string} videoId - YouTube video ID
 * @returns {Promise<Object>} - Captions data with track URLs
 */
async function fetchCaptionTracks(videoId) {
  const videoUrl = `https://www.youtube.com/watch?v=${videoId}`;

  // Fetch the video page
  const response = await fetch(videoUrl);
  if (!response.ok) {
    throw new Error(`Failed to fetch video page: ${response.status}`);
  }

  const html = await response.text();

  // Extract the player response JSON from the page
  // Look for ytInitialPlayerResponse variable
  const playerResponseMatch = html.match(/ytInitialPlayerResponse\s*=\s*({.+?});(?:\s*var\s|\s*<\/script>)/);

  if (!playerResponseMatch) {
    throw new Error('Could not find player response in video page');
  }

  let playerResponse;
  try {
    playerResponse = JSON.parse(playerResponseMatch[1]);
  } catch (e) {
    throw new Error('Failed to parse player response JSON');
  }

  // Extract captions from player response
  const captions = playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks;

  if (!captions || captions.length === 0) {
    throw new Error('No captions available for this video');
  }

  return {
    tracks: captions.map(track => ({
      languageCode: track.languageCode,
      name: track.name?.simpleText || track.languageCode,
      baseUrl: track.baseUrl,
      isAutoGenerated: track.kind === 'asr'
    })),
    videoId
  };
}

/**
 * Parse VTT/XML subtitle format into structured array
 * @param {string} content - Raw subtitle content (XML format from YouTube)
 * @returns {Array<{start: number, dur: number, text: string}>}
 */
function parseSubtitleXml(content) {
  const subtitles = [];

  // YouTube returns XML format like: <text start="0.5" dur="2.3">Hello</text>
  const regex = /<text[^>]*start="([^"]*)"[^>]*dur="([^"]*)"[^>]*>([\s\S]*?)<\/text>/g;

  let match;
  while ((match = regex.exec(content)) !== null) {
    const start = parseFloat(match[1]);
    const dur = parseFloat(match[2]);
    // Decode HTML entities and clean up the text
    let text = match[3]
      .replace(/&amp;/g, '&')
      .replace(/&lt;/g, '<')
      .replace(/&gt;/g, '>')
      .replace(/&quot;/g, '"')
      .replace(/&#39;/g, "'")
      .replace(/\n/g, ' ')
      .trim();

    if (text) {
      subtitles.push({ start, dur, text });
    }
  }

  return subtitles;
}

/**
 * Fetch subtitles for a YouTube video
 * @param {Object} options - Fetch options
 * @param {string} options.videoID - YouTube video ID
 * @param {string} [options.lang='en'] - Language code (e.g., 'en', 'fr', 'zh')
 * @returns {Promise<Array<{start: number, dur: number, text: string}>>}
 */
export async function getSubtitles({ videoID, lang = 'en' }) {
  if (!videoID) {
    throw new Error('Video ID is required');
  }

  // Fetch available caption tracks
  const captionData = await fetchCaptionTracks(videoID);

  // Find the requested language track
  let selectedTrack = captionData.tracks.find(track =>
    track.languageCode === lang ||
    track.languageCode.startsWith(lang + '-')
  );

  // Fallback to English if requested language not found
  if (!selectedTrack && lang !== 'en') {
    selectedTrack = captionData.tracks.find(track =>
      track.languageCode === 'en' ||
      track.languageCode.startsWith('en-')
    );
  }

  // Use first available track as last resort
  if (!selectedTrack) {
    selectedTrack = captionData.tracks[0];
  }

  if (!selectedTrack || !selectedTrack.baseUrl) {
    throw new Error(`No captions found for language: ${lang}`);
  }

  // Fetch the subtitle content
  const subtitleUrl = selectedTrack.baseUrl;
  const response = await fetch(subtitleUrl);

  if (!response.ok) {
    throw new Error(`Failed to fetch subtitles: ${response.status}`);
  }

  const content = await response.text();
  return parseSubtitleXml(content);
}

/**
 * Get available subtitle languages for a video
 * @param {string} videoID - YouTube video ID
 * @returns {Promise<Array<{languageCode: string, name: string, isAutoGenerated: boolean}>>}
 */
export async function getAvailableLanguages(videoID) {
  const captionData = await fetchCaptionTracks(videoID);
  return captionData.tracks;
}

/**
 * Convert subtitle array to SRT format string
 * @param {Array<{start: number, dur: number, text: string}>} subtitles
 * @returns {string}
 */
export function toSrtFormat(subtitles) {
  return subtitles.map((sub, index) => {
    const startTime = formatSrtTime(sub.start);
    const endTime = formatSrtTime(sub.start + sub.dur);
    return `${index + 1}\n${startTime} --> ${endTime}\n${sub.text}\n`;
  }).join('\n');
}

/**
 * Convert subtitle array to scrolling text format (for display)
 * @param {Array<{start: number, dur: number, text: string}>} subtitles
 * @returns {string}
 */
export function toScrollingFormat(subtitles) {
  return subtitles.map(sub => {
    const startTime = formatDisplayTime(sub.start);
    const endTime = formatDisplayTime(sub.start + sub.dur);
    return `${startTime} --> ${endTime}\n${sub.text}`;
  }).join('\n\n');
}

/**
 * Format seconds to SRT time format (HH:MM:SS,mmm)
 * @param {number} seconds
 * @returns {string}
 */
function formatSrtTime(seconds) {
  const hours = Math.floor(seconds / 3600);
  const mins = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);
  const ms = Math.floor((seconds % 1) * 1000);
  return `${String(hours).padStart(2, '0')}:${String(mins).padStart(2, '0')}:${String(secs).padStart(2, '0')},${String(ms).padStart(3, '0')}`;
}

/**
 * Format seconds to display time format (MM:SS)
 * @param {number} seconds
 * @returns {string}
 */
function formatDisplayTime(seconds) {
  const mins = Math.floor(seconds / 60);
  const secs = Math.floor(seconds % 60);
  return `${String(mins).padStart(2, '0')}:${String(secs).padStart(2, '0')}`;
}

/**
 * Main function to fetch YouTube subtitles with URL or ID input
 * Compatible interface for easy integration
 * @param {string} videoUrlOrId - YouTube video URL or video ID
 * @param {string} [lang='en'] - Language code
 * @returns {Promise<{subtitles: Array, scrollingText: string, srtText: string}>}
 */
export async function fetchYouTubeSubtitles(videoUrlOrId, lang = 'en') {
  const videoID = extractVideoId(videoUrlOrId);

  if (!videoID) {
    throw new Error('Invalid YouTube URL or video ID');
  }

  const subtitles = await getSubtitles({ videoID, lang });

  return {
    videoID,
    subtitles,
    scrollingText: toScrollingFormat(subtitles),
    srtText: toSrtFormat(subtitles),
    language: lang
  };
}

export default {
  extractVideoId,
  getSubtitles,
  getAvailableLanguages,
  fetchYouTubeSubtitles,
  toSrtFormat,
  toScrollingFormat
};
